services:
  dev-server:
    build: .
    ports:
      - "3009:3009"
    volumes:
      - "./src:/app/src"
      - "./gradle.build:/app/gradle.build"
      - "./package.json:/app/package.json"
      - "~/.m2:/root/.m2"
    working_dir: /app
    command: ["watchexec", "--watch", "src", "--exts", "java", "--restart", "gradle run"]
    init: true # to ensure signal handling works (and you can kill the container with ctrl-c)
  exercises:
    profiles: ["exercises"] # exclude from "docker-compose up"
    build: .
    volumes:
      - "./src:/app/src"
      - "./gradle.build:/app/gradle.build"
      - "~/.m2:/root/.m2"
    command: ["/bin/bash"]
